package com.mljr.yulv.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CaAppFlowExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    public CaAppFlowExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andFlowSeqIsNull() {
            addCriterion("FLOW_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andFlowSeqIsNotNull() {
            addCriterion("FLOW_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andFlowSeqEqualTo(Integer value) {
            addCriterion("FLOW_SEQ =", value, "flowSeq");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNotEqualTo(Integer value) {
            addCriterion("FLOW_SEQ <>", value, "flowSeq");
            return (Criteria) this;
        }

        public Criteria andFlowSeqGreaterThan(Integer value) {
            addCriterion("FLOW_SEQ >", value, "flowSeq");
            return (Criteria) this;
        }

        public Criteria andFlowSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("FLOW_SEQ >=", value, "flowSeq");
            return (Criteria) this;
        }

        public Criteria andFlowSeqLessThan(Integer value) {
            addCriterion("FLOW_SEQ <", value, "flowSeq");
            return (Criteria) this;
        }

        public Criteria andFlowSeqLessThanOrEqualTo(Integer value) {
            addCriterion("FLOW_SEQ <=", value, "flowSeq");
            return (Criteria) this;
        }

        public Criteria andFlowSeqIn(List<Integer> values) {
            addCriterion("FLOW_SEQ in", values, "flowSeq");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNotIn(List<Integer> values) {
            addCriterion("FLOW_SEQ not in", values, "flowSeq");
            return (Criteria) this;
        }

        public Criteria andFlowSeqBetween(Integer value1, Integer value2) {
            addCriterion("FLOW_SEQ between", value1, value2, "flowSeq");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("FLOW_SEQ not between", value1, value2, "flowSeq");
            return (Criteria) this;
        }

        public Criteria andFlowNoIsNull() {
            addCriterion("FLOW_NO is null");
            return (Criteria) this;
        }

        public Criteria andFlowNoIsNotNull() {
            addCriterion("FLOW_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFlowNoEqualTo(Integer value) {
            addCriterion("FLOW_NO =", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoNotEqualTo(Integer value) {
            addCriterion("FLOW_NO <>", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoGreaterThan(Integer value) {
            addCriterion("FLOW_NO >", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("FLOW_NO >=", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoLessThan(Integer value) {
            addCriterion("FLOW_NO <", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoLessThanOrEqualTo(Integer value) {
            addCriterion("FLOW_NO <=", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoIn(List<Integer> values) {
            addCriterion("FLOW_NO in", values, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoNotIn(List<Integer> values) {
            addCriterion("FLOW_NO not in", values, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoBetween(Integer value1, Integer value2) {
            addCriterion("FLOW_NO between", value1, value2, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoNotBetween(Integer value1, Integer value2) {
            addCriterion("FLOW_NO not between", value1, value2, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameIsNull() {
            addCriterion("FLOW_SEQ_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameIsNotNull() {
            addCriterion("FLOW_SEQ_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameEqualTo(String value) {
            addCriterion("FLOW_SEQ_NAME =", value, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameNotEqualTo(String value) {
            addCriterion("FLOW_SEQ_NAME <>", value, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameGreaterThan(String value) {
            addCriterion("FLOW_SEQ_NAME >", value, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameGreaterThanOrEqualTo(String value) {
            addCriterion("FLOW_SEQ_NAME >=", value, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameLessThan(String value) {
            addCriterion("FLOW_SEQ_NAME <", value, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameLessThanOrEqualTo(String value) {
            addCriterion("FLOW_SEQ_NAME <=", value, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameLike(String value) {
            addCriterion("FLOW_SEQ_NAME like", value, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameNotLike(String value) {
            addCriterion("FLOW_SEQ_NAME not like", value, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameIn(List<String> values) {
            addCriterion("FLOW_SEQ_NAME in", values, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameNotIn(List<String> values) {
            addCriterion("FLOW_SEQ_NAME not in", values, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameBetween(String value1, String value2) {
            addCriterion("FLOW_SEQ_NAME between", value1, value2, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andFlowSeqNameNotBetween(String value1, String value2) {
            addCriterion("FLOW_SEQ_NAME not between", value1, value2, "flowSeqName");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPreStatusIsNull() {
            addCriterion("PRE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andPreStatusIsNotNull() {
            addCriterion("PRE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andPreStatusEqualTo(String value) {
            addCriterion("PRE_STATUS =", value, "preStatus");
            return (Criteria) this;
        }

        public Criteria andPreStatusNotEqualTo(String value) {
            addCriterion("PRE_STATUS <>", value, "preStatus");
            return (Criteria) this;
        }

        public Criteria andPreStatusGreaterThan(String value) {
            addCriterion("PRE_STATUS >", value, "preStatus");
            return (Criteria) this;
        }

        public Criteria andPreStatusGreaterThanOrEqualTo(String value) {
            addCriterion("PRE_STATUS >=", value, "preStatus");
            return (Criteria) this;
        }

        public Criteria andPreStatusLessThan(String value) {
            addCriterion("PRE_STATUS <", value, "preStatus");
            return (Criteria) this;
        }

        public Criteria andPreStatusLessThanOrEqualTo(String value) {
            addCriterion("PRE_STATUS <=", value, "preStatus");
            return (Criteria) this;
        }

        public Criteria andPreStatusLike(String value) {
            addCriterion("PRE_STATUS like", value, "preStatus");
            return (Criteria) this;
        }

        public Criteria andPreStatusNotLike(String value) {
            addCriterion("PRE_STATUS not like", value, "preStatus");
            return (Criteria) this;
        }

        public Criteria andPreStatusIn(List<String> values) {
            addCriterion("PRE_STATUS in", values, "preStatus");
            return (Criteria) this;
        }

        public Criteria andPreStatusNotIn(List<String> values) {
            addCriterion("PRE_STATUS not in", values, "preStatus");
            return (Criteria) this;
        }

        public Criteria andPreStatusBetween(String value1, String value2) {
            addCriterion("PRE_STATUS between", value1, value2, "preStatus");
            return (Criteria) this;
        }

        public Criteria andPreStatusNotBetween(String value1, String value2) {
            addCriterion("PRE_STATUS not between", value1, value2, "preStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusIsNull() {
            addCriterion("NEXT_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andNextStatusIsNotNull() {
            addCriterion("NEXT_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andNextStatusEqualTo(String value) {
            addCriterion("NEXT_STATUS =", value, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusNotEqualTo(String value) {
            addCriterion("NEXT_STATUS <>", value, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusGreaterThan(String value) {
            addCriterion("NEXT_STATUS >", value, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusGreaterThanOrEqualTo(String value) {
            addCriterion("NEXT_STATUS >=", value, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusLessThan(String value) {
            addCriterion("NEXT_STATUS <", value, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusLessThanOrEqualTo(String value) {
            addCriterion("NEXT_STATUS <=", value, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusLike(String value) {
            addCriterion("NEXT_STATUS like", value, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusNotLike(String value) {
            addCriterion("NEXT_STATUS not like", value, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusIn(List<String> values) {
            addCriterion("NEXT_STATUS in", values, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusNotIn(List<String> values) {
            addCriterion("NEXT_STATUS not in", values, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusBetween(String value1, String value2) {
            addCriterion("NEXT_STATUS between", value1, value2, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andNextStatusNotBetween(String value1, String value2) {
            addCriterion("NEXT_STATUS not between", value1, value2, "nextStatus");
            return (Criteria) this;
        }

        public Criteria andBeginDateIsNull() {
            addCriterion("BEGIN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andBeginDateIsNotNull() {
            addCriterion("BEGIN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andBeginDateEqualTo(Date value) {
            addCriterionForJDBCDate("BEGIN_DATE =", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("BEGIN_DATE <>", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateGreaterThan(Date value) {
            addCriterionForJDBCDate("BEGIN_DATE >", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("BEGIN_DATE >=", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateLessThan(Date value) {
            addCriterionForJDBCDate("BEGIN_DATE <", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("BEGIN_DATE <=", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateIn(List<Date> values) {
            addCriterionForJDBCDate("BEGIN_DATE in", values, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("BEGIN_DATE not in", values, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("BEGIN_DATE between", value1, value2, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("BEGIN_DATE not between", value1, value2, "beginDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("END_DATE =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("END_DATE <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("END_DATE >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("END_DATE >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterionForJDBCDate("END_DATE <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("END_DATE <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("END_DATE in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("END_DATE not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("END_DATE between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("END_DATE not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andVarIsNull() {
            addCriterion("VAR is null");
            return (Criteria) this;
        }

        public Criteria andVarIsNotNull() {
            addCriterion("VAR is not null");
            return (Criteria) this;
        }

        public Criteria andVarEqualTo(Byte value) {
            addCriterion("VAR =", value, "var");
            return (Criteria) this;
        }

        public Criteria andVarNotEqualTo(Byte value) {
            addCriterion("VAR <>", value, "var");
            return (Criteria) this;
        }

        public Criteria andVarGreaterThan(Byte value) {
            addCriterion("VAR >", value, "var");
            return (Criteria) this;
        }

        public Criteria andVarGreaterThanOrEqualTo(Byte value) {
            addCriterion("VAR >=", value, "var");
            return (Criteria) this;
        }

        public Criteria andVarLessThan(Byte value) {
            addCriterion("VAR <", value, "var");
            return (Criteria) this;
        }

        public Criteria andVarLessThanOrEqualTo(Byte value) {
            addCriterion("VAR <=", value, "var");
            return (Criteria) this;
        }

        public Criteria andVarIn(List<Byte> values) {
            addCriterion("VAR in", values, "var");
            return (Criteria) this;
        }

        public Criteria andVarNotIn(List<Byte> values) {
            addCriterion("VAR not in", values, "var");
            return (Criteria) this;
        }

        public Criteria andVarBetween(Byte value1, Byte value2) {
            addCriterion("VAR between", value1, value2, "var");
            return (Criteria) this;
        }

        public Criteria andVarNotBetween(Byte value1, Byte value2) {
            addCriterion("VAR not between", value1, value2, "var");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("USER_NAME in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andIsGpsIsNull() {
            addCriterion("IS_GPS is null");
            return (Criteria) this;
        }

        public Criteria andIsGpsIsNotNull() {
            addCriterion("IS_GPS is not null");
            return (Criteria) this;
        }

        public Criteria andIsGpsEqualTo(String value) {
            addCriterion("IS_GPS =", value, "isGps");
            return (Criteria) this;
        }

        public Criteria andIsGpsNotEqualTo(String value) {
            addCriterion("IS_GPS <>", value, "isGps");
            return (Criteria) this;
        }

        public Criteria andIsGpsGreaterThan(String value) {
            addCriterion("IS_GPS >", value, "isGps");
            return (Criteria) this;
        }

        public Criteria andIsGpsGreaterThanOrEqualTo(String value) {
            addCriterion("IS_GPS >=", value, "isGps");
            return (Criteria) this;
        }

        public Criteria andIsGpsLessThan(String value) {
            addCriterion("IS_GPS <", value, "isGps");
            return (Criteria) this;
        }

        public Criteria andIsGpsLessThanOrEqualTo(String value) {
            addCriterion("IS_GPS <=", value, "isGps");
            return (Criteria) this;
        }

        public Criteria andIsGpsLike(String value) {
            addCriterion("IS_GPS like", value, "isGps");
            return (Criteria) this;
        }

        public Criteria andIsGpsNotLike(String value) {
            addCriterion("IS_GPS not like", value, "isGps");
            return (Criteria) this;
        }

        public Criteria andIsGpsIn(List<String> values) {
            addCriterion("IS_GPS in", values, "isGps");
            return (Criteria) this;
        }

        public Criteria andIsGpsNotIn(List<String> values) {
            addCriterion("IS_GPS not in", values, "isGps");
            return (Criteria) this;
        }

        public Criteria andIsGpsBetween(String value1, String value2) {
            addCriterion("IS_GPS between", value1, value2, "isGps");
            return (Criteria) this;
        }

        public Criteria andIsGpsNotBetween(String value1, String value2) {
            addCriterion("IS_GPS not between", value1, value2, "isGps");
            return (Criteria) this;
        }

        public Criteria andUploadGpsIsNull() {
            addCriterion("UPLOAD_GPS is null");
            return (Criteria) this;
        }

        public Criteria andUploadGpsIsNotNull() {
            addCriterion("UPLOAD_GPS is not null");
            return (Criteria) this;
        }

        public Criteria andUploadGpsEqualTo(Byte value) {
            addCriterion("UPLOAD_GPS =", value, "uploadGps");
            return (Criteria) this;
        }

        public Criteria andUploadGpsNotEqualTo(Byte value) {
            addCriterion("UPLOAD_GPS <>", value, "uploadGps");
            return (Criteria) this;
        }

        public Criteria andUploadGpsGreaterThan(Byte value) {
            addCriterion("UPLOAD_GPS >", value, "uploadGps");
            return (Criteria) this;
        }

        public Criteria andUploadGpsGreaterThanOrEqualTo(Byte value) {
            addCriterion("UPLOAD_GPS >=", value, "uploadGps");
            return (Criteria) this;
        }

        public Criteria andUploadGpsLessThan(Byte value) {
            addCriterion("UPLOAD_GPS <", value, "uploadGps");
            return (Criteria) this;
        }

        public Criteria andUploadGpsLessThanOrEqualTo(Byte value) {
            addCriterion("UPLOAD_GPS <=", value, "uploadGps");
            return (Criteria) this;
        }

        public Criteria andUploadGpsIn(List<Byte> values) {
            addCriterion("UPLOAD_GPS in", values, "uploadGps");
            return (Criteria) this;
        }

        public Criteria andUploadGpsNotIn(List<Byte> values) {
            addCriterion("UPLOAD_GPS not in", values, "uploadGps");
            return (Criteria) this;
        }

        public Criteria andUploadGpsBetween(Byte value1, Byte value2) {
            addCriterion("UPLOAD_GPS between", value1, value2, "uploadGps");
            return (Criteria) this;
        }

        public Criteria andUploadGpsNotBetween(Byte value1, Byte value2) {
            addCriterion("UPLOAD_GPS not between", value1, value2, "uploadGps");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ca_app_flow
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}