package com.mljr.yulv.dao.mapper;

import com.mljr.yulv.dao.BaseMapper;
import com.mljr.yulv.dao.domain.CaAppFlow;
import com.mljr.yulv.dao.domain.CaAppFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaAppFlowMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    long countByExample(CaAppFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("flowSeq") Integer flowSeq, @Param("flowNo") Integer flowNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    int insert(CaAppFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    int insertSelective(CaAppFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    List<CaAppFlow> selectByExample(CaAppFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    CaAppFlow selectByPrimaryKey(@Param("flowSeq") Integer flowSeq, @Param("flowNo") Integer flowNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CaAppFlow record, @Param("example") CaAppFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CaAppFlow record, @Param("example") CaAppFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CaAppFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CaAppFlow record);
}