package com.hy.dynamicdatasource.dao.domain;

import com.hy.dynamicdatasource.dao.BaseModel;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ca_app_flow
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CaAppFlow extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.FLOW_SEQ
     *
     * @mbg.generated
     */
    private Integer flowSeq;

    /**
     * Database Column Remarks:
     *   按流程先后顺序排序，从1开始
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.FLOW_NO
     *
     * @mbg.generated
     */
    private Integer flowNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.FLOW_SEQ_NAME
     *
     * @mbg.generated
     */
    private String flowSeqName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.PRE_STATUS
     *
     * @mbg.generated
     */
    private String preStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.NEXT_STATUS
     *
     * @mbg.generated
     */
    private String nextStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.BEGIN_DATE
     *
     * @mbg.generated
     */
    private Date beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.END_DATE
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.VAR
     *
     * @mbg.generated
     */
    private Byte var;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.USER_ID
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.IS_GPS
     *
     * @mbg.generated
     */
    private String isGps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_flow.UPLOAD_GPS
     *
     * @mbg.generated
     */
    private Byte uploadGps;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.FLOW_SEQ
     *
     * @return the value of ca_app_flow.FLOW_SEQ
     *
     * @mbg.generated
     */
    public Integer getFlowSeq() {
        return flowSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.FLOW_SEQ
     *
     * @param flowSeq the value for ca_app_flow.FLOW_SEQ
     *
     * @mbg.generated
     */
    public void setFlowSeq(Integer flowSeq) {
        this.flowSeq = flowSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.FLOW_NO
     *
     * @return the value of ca_app_flow.FLOW_NO
     *
     * @mbg.generated
     */
    public Integer getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.FLOW_NO
     *
     * @param flowNo the value for ca_app_flow.FLOW_NO
     *
     * @mbg.generated
     */
    public void setFlowNo(Integer flowNo) {
        this.flowNo = flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.FLOW_SEQ_NAME
     *
     * @return the value of ca_app_flow.FLOW_SEQ_NAME
     *
     * @mbg.generated
     */
    public String getFlowSeqName() {
        return flowSeqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.FLOW_SEQ_NAME
     *
     * @param flowSeqName the value for ca_app_flow.FLOW_SEQ_NAME
     *
     * @mbg.generated
     */
    public void setFlowSeqName(String flowSeqName) {
        this.flowSeqName = flowSeqName == null ? null : flowSeqName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.STATUS
     *
     * @return the value of ca_app_flow.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.STATUS
     *
     * @param status the value for ca_app_flow.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.PRE_STATUS
     *
     * @return the value of ca_app_flow.PRE_STATUS
     *
     * @mbg.generated
     */
    public String getPreStatus() {
        return preStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.PRE_STATUS
     *
     * @param preStatus the value for ca_app_flow.PRE_STATUS
     *
     * @mbg.generated
     */
    public void setPreStatus(String preStatus) {
        this.preStatus = preStatus == null ? null : preStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.NEXT_STATUS
     *
     * @return the value of ca_app_flow.NEXT_STATUS
     *
     * @mbg.generated
     */
    public String getNextStatus() {
        return nextStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.NEXT_STATUS
     *
     * @param nextStatus the value for ca_app_flow.NEXT_STATUS
     *
     * @mbg.generated
     */
    public void setNextStatus(String nextStatus) {
        this.nextStatus = nextStatus == null ? null : nextStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.BEGIN_DATE
     *
     * @return the value of ca_app_flow.BEGIN_DATE
     *
     * @mbg.generated
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.BEGIN_DATE
     *
     * @param beginDate the value for ca_app_flow.BEGIN_DATE
     *
     * @mbg.generated
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.END_DATE
     *
     * @return the value of ca_app_flow.END_DATE
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.END_DATE
     *
     * @param endDate the value for ca_app_flow.END_DATE
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.VAR
     *
     * @return the value of ca_app_flow.VAR
     *
     * @mbg.generated
     */
    public Byte getVar() {
        return var;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.VAR
     *
     * @param var the value for ca_app_flow.VAR
     *
     * @mbg.generated
     */
    public void setVar(Byte var) {
        this.var = var;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.CREATE_TIME
     *
     * @return the value of ca_app_flow.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.CREATE_TIME
     *
     * @param createTime the value for ca_app_flow.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.USER_ID
     *
     * @return the value of ca_app_flow.USER_ID
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.USER_ID
     *
     * @param userId the value for ca_app_flow.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.USER_NAME
     *
     * @return the value of ca_app_flow.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.USER_NAME
     *
     * @param userName the value for ca_app_flow.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.REMARKS
     *
     * @return the value of ca_app_flow.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.REMARKS
     *
     * @param remarks the value for ca_app_flow.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.IS_GPS
     *
     * @return the value of ca_app_flow.IS_GPS
     *
     * @mbg.generated
     */
    public String getIsGps() {
        return isGps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.IS_GPS
     *
     * @param isGps the value for ca_app_flow.IS_GPS
     *
     * @mbg.generated
     */
    public void setIsGps(String isGps) {
        this.isGps = isGps == null ? null : isGps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_flow.UPLOAD_GPS
     *
     * @return the value of ca_app_flow.UPLOAD_GPS
     *
     * @mbg.generated
     */
    public Byte getUploadGps() {
        return uploadGps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_flow.UPLOAD_GPS
     *
     * @param uploadGps the value for ca_app_flow.UPLOAD_GPS
     *
     * @mbg.generated
     */
    public void setUploadGps(Byte uploadGps) {
        this.uploadGps = uploadGps;
    }
}