package com.hy.dynamicdatasource.dao.domain;

import com.hy.dynamicdatasource.dao.BaseModel;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ca_app_info_extend
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CaAppInfoExtend extends BaseModel {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   申请单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.app_code
     *
     * @mbg.generated
     */
    private String appCode;

    /**
     * Database Column Remarks:
     *   收取方式（1，线上收取；2，线下收取）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.taken_mode
     *
     * @mbg.generated
     */
    private Integer takenMode;

    /**
     * Database Column Remarks:
     *   线下平台费支付结果(1、已支付 2、未支付)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.offline_com_fee_pay_status
     *
     * @mbg.generated
     */
    private Integer offlineComFeePayStatus;

    /**
     * Database Column Remarks:
     *   线下平台费支付结果
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.offline_com_fee_pay_result
     *
     * @mbg.generated
     */
    private String offlineComFeePayResult;

    /**
     * Database Column Remarks:
     *   替换之前的旧产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.old_product_name
     *
     * @mbg.generated
     */
    private String oldProductName;

    /**
     * Database Column Remarks:
     *   高风险平台费利率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.high_com_rate
     *
     * @mbg.generated
     */
    private BigDecimal highComRate;

    /**
     * Database Column Remarks:
     *   高风险贷款利率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.high_rate
     *
     * @mbg.generated
     */
    private BigDecimal highRate;

    /**
     * Database Column Remarks:
     *   高风险产品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.high_product_id
     *
     * @mbg.generated
     */
    private Integer highProductId;

    /**
     * Database Column Remarks:
     *   -1:默认 0显示高风险高定价产品 1不显示
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.show_high_rate
     *
     * @mbg.generated
     */
    private Integer showHighRate;

    /**
     * Database Column Remarks:
     *   产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.high_rate_product
     *
     * @mbg.generated
     */
    private String highRateProduct;

    /**
     * Database Column Remarks:
     *   是否选择高风险产品 (1,同意，2不同意)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.is_agree_high_risk_product
     *
     * @mbg.generated
     */
    private Integer isAgreeHighRiskProduct;

    /**
     * Database Column Remarks:
     *   0默认  1没有配置高风险  2原产品 3高风险产品 4高风险拒绝
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.high_type
     *
     * @mbg.generated
     */
    private Integer highType;

    /**
     * Database Column Remarks:
     *   资金方回款成功状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.new_loan_status
     *
     * @mbg.generated
     */
    private Integer newLoanStatus;

    /**
     * Database Column Remarks:
     *   是否自动请款 1：是  0：否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.is_auto_loan
     *
     * @mbg.generated
     */
    private Integer isAutoLoan;

    /**
     * Database Column Remarks:
     *   申请成功时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.apply_time
     *
     * @mbg.generated
     */
    private Date applyTime;

    /**
     * Database Column Remarks:
     *   先放后抵流程一级分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.one_level
     *
     * @mbg.generated
     */
    private Integer oneLevel;

    /**
     * Database Column Remarks:
     *   先放后抵流程二级分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.two_level
     *
     * @mbg.generated
     */
    private Integer twoLevel;

    /**
     * Database Column Remarks:
     *   客户是否到场
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.arrive
     *
     * @mbg.generated
     */
    private String arrive;

    /**
     * Database Column Remarks:
     *   0通过  1等待中
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.final_wait
     *
     * @mbg.generated
     */
    private Integer finalWait;

    /**
     * Database Column Remarks:
     *   初审第一次提交时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.first_examine_time
     *
     * @mbg.generated
     */
    private Date firstExamineTime;

    /**
     * Database Column Remarks:
     *   复审第一次提交时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.second_examine_time
     *
     * @mbg.generated
     */
    private Date secondExamineTime;

    /**
     * Database Column Remarks:
     *   终审第一次提交时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.final_examine_time
     *
     * @mbg.generated
     */
    private Date finalExamineTime;

    /**
     * Database Column Remarks:
     *   贷前第一次提交时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.loan_before_time
     *
     * @mbg.generated
     */
    private Date loanBeforeTime;

    /**
     * Database Column Remarks:
     *   子状态码(1:终审领单)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.sub_status
     *
     * @mbg.generated
     */
    private Integer subStatus;

    /**
     * Database Column Remarks:
     *   订单小状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.flow_status
     *
     * @mbg.generated
     */
    private Integer flowStatus;

    /**
     * Database Column Remarks:
     *   资金方简称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.fund_code
     *
     * @mbg.generated
     */
    private String fundCode;

    /**
     * Database Column Remarks:
     *   运营留言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     * Database Column Remarks:
     *   审批用户编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   领子状态 0默认 1天枢领单 2力蕴领单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.accept_status
     *
     * @mbg.generated
     */
    private Integer acceptStatus;

    /**
     * Database Column Remarks:
     *   loanToValue状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.ltv_status
     *
     * @mbg.generated
     */
    private Integer ltvStatus;

    /**
     * Database Column Remarks:
     *   降额批复类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.ltv_type
     *
     * @mbg.generated
     */
    private Integer ltvType;

    /**
     * Database Column Remarks:
     *   loanToValue最大通过值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.ltv_amount
     *
     * @mbg.generated
     */
    private BigDecimal ltvAmount;

    /**
     * Database Column Remarks:
     *   历史数据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.historical_records
     *
     * @mbg.generated
     */
    private String historicalRecords;

    /**
     * Database Column Remarks:
     *   优质用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.high_quality_user
     *
     * @mbg.generated
     */
    private Integer highQualityUser;

    /**
     * Database Column Remarks:
     *   优质用户辅助状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.high_quality_user_status
     *
     * @mbg.generated
     */
    private Integer highQualityUserStatus;

    /**
     * Database Column Remarks:
     *   第一次上传贷后附件时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.first_upload_after_annex_time
     *
     * @mbg.generated
     */
    private Date firstUploadAfterAnnexTime;

    /**
     * Database Column Remarks:
     *   最后一次上传贷后附件时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.last_upload_after_annex_time
     *
     * @mbg.generated
     */
    private Date lastUploadAfterAnnexTime;

    /**
     * Database Column Remarks:
     *   资方成本利率(%)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.cost_rate
     *
     * @mbg.generated
     */
    private BigDecimal costRate;

    /**
     * Database Column Remarks:
     *   订单状态更新时间说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.status_update_desc
     *
     * @mbg.generated
     */
    private String statusUpdateDesc;

    /**
     * Database Column Remarks:
     *   订单状态更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.status_update_time
     *
     * @mbg.generated
     */
    private Date statusUpdateTime;

    /**
     * Database Column Remarks:
     *   平台费定价标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.ser_fin_label
     *
     * @mbg.generated
     */
    private String serFinLabel;

    /**
     * Database Column Remarks:
     *   车辆保险费规则id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.car_secure_rule_id
     *
     * @mbg.generated
     */
    private Integer carSecureRuleId;

    /**
     * Database Column Remarks:
     *   微众一审结果
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_app_info_extend.webank_first_result
     *
     * @mbg.generated
     */
    private String webankFirstResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.id
     *
     * @return the value of ca_app_info_extend.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.id
     *
     * @param id the value for ca_app_info_extend.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.app_code
     *
     * @return the value of ca_app_info_extend.app_code
     *
     * @mbg.generated
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.app_code
     *
     * @param appCode the value for ca_app_info_extend.app_code
     *
     * @mbg.generated
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.taken_mode
     *
     * @return the value of ca_app_info_extend.taken_mode
     *
     * @mbg.generated
     */
    public Integer getTakenMode() {
        return takenMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.taken_mode
     *
     * @param takenMode the value for ca_app_info_extend.taken_mode
     *
     * @mbg.generated
     */
    public void setTakenMode(Integer takenMode) {
        this.takenMode = takenMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.offline_com_fee_pay_status
     *
     * @return the value of ca_app_info_extend.offline_com_fee_pay_status
     *
     * @mbg.generated
     */
    public Integer getOfflineComFeePayStatus() {
        return offlineComFeePayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.offline_com_fee_pay_status
     *
     * @param offlineComFeePayStatus the value for ca_app_info_extend.offline_com_fee_pay_status
     *
     * @mbg.generated
     */
    public void setOfflineComFeePayStatus(Integer offlineComFeePayStatus) {
        this.offlineComFeePayStatus = offlineComFeePayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.offline_com_fee_pay_result
     *
     * @return the value of ca_app_info_extend.offline_com_fee_pay_result
     *
     * @mbg.generated
     */
    public String getOfflineComFeePayResult() {
        return offlineComFeePayResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.offline_com_fee_pay_result
     *
     * @param offlineComFeePayResult the value for ca_app_info_extend.offline_com_fee_pay_result
     *
     * @mbg.generated
     */
    public void setOfflineComFeePayResult(String offlineComFeePayResult) {
        this.offlineComFeePayResult = offlineComFeePayResult == null ? null : offlineComFeePayResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.old_product_name
     *
     * @return the value of ca_app_info_extend.old_product_name
     *
     * @mbg.generated
     */
    public String getOldProductName() {
        return oldProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.old_product_name
     *
     * @param oldProductName the value for ca_app_info_extend.old_product_name
     *
     * @mbg.generated
     */
    public void setOldProductName(String oldProductName) {
        this.oldProductName = oldProductName == null ? null : oldProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.high_com_rate
     *
     * @return the value of ca_app_info_extend.high_com_rate
     *
     * @mbg.generated
     */
    public BigDecimal getHighComRate() {
        return highComRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.high_com_rate
     *
     * @param highComRate the value for ca_app_info_extend.high_com_rate
     *
     * @mbg.generated
     */
    public void setHighComRate(BigDecimal highComRate) {
        this.highComRate = highComRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.high_rate
     *
     * @return the value of ca_app_info_extend.high_rate
     *
     * @mbg.generated
     */
    public BigDecimal getHighRate() {
        return highRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.high_rate
     *
     * @param highRate the value for ca_app_info_extend.high_rate
     *
     * @mbg.generated
     */
    public void setHighRate(BigDecimal highRate) {
        this.highRate = highRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.high_product_id
     *
     * @return the value of ca_app_info_extend.high_product_id
     *
     * @mbg.generated
     */
    public Integer getHighProductId() {
        return highProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.high_product_id
     *
     * @param highProductId the value for ca_app_info_extend.high_product_id
     *
     * @mbg.generated
     */
    public void setHighProductId(Integer highProductId) {
        this.highProductId = highProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.show_high_rate
     *
     * @return the value of ca_app_info_extend.show_high_rate
     *
     * @mbg.generated
     */
    public Integer getShowHighRate() {
        return showHighRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.show_high_rate
     *
     * @param showHighRate the value for ca_app_info_extend.show_high_rate
     *
     * @mbg.generated
     */
    public void setShowHighRate(Integer showHighRate) {
        this.showHighRate = showHighRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.high_rate_product
     *
     * @return the value of ca_app_info_extend.high_rate_product
     *
     * @mbg.generated
     */
    public String getHighRateProduct() {
        return highRateProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.high_rate_product
     *
     * @param highRateProduct the value for ca_app_info_extend.high_rate_product
     *
     * @mbg.generated
     */
    public void setHighRateProduct(String highRateProduct) {
        this.highRateProduct = highRateProduct == null ? null : highRateProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.is_agree_high_risk_product
     *
     * @return the value of ca_app_info_extend.is_agree_high_risk_product
     *
     * @mbg.generated
     */
    public Integer getIsAgreeHighRiskProduct() {
        return isAgreeHighRiskProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.is_agree_high_risk_product
     *
     * @param isAgreeHighRiskProduct the value for ca_app_info_extend.is_agree_high_risk_product
     *
     * @mbg.generated
     */
    public void setIsAgreeHighRiskProduct(Integer isAgreeHighRiskProduct) {
        this.isAgreeHighRiskProduct = isAgreeHighRiskProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.high_type
     *
     * @return the value of ca_app_info_extend.high_type
     *
     * @mbg.generated
     */
    public Integer getHighType() {
        return highType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.high_type
     *
     * @param highType the value for ca_app_info_extend.high_type
     *
     * @mbg.generated
     */
    public void setHighType(Integer highType) {
        this.highType = highType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.new_loan_status
     *
     * @return the value of ca_app_info_extend.new_loan_status
     *
     * @mbg.generated
     */
    public Integer getNewLoanStatus() {
        return newLoanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.new_loan_status
     *
     * @param newLoanStatus the value for ca_app_info_extend.new_loan_status
     *
     * @mbg.generated
     */
    public void setNewLoanStatus(Integer newLoanStatus) {
        this.newLoanStatus = newLoanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.is_auto_loan
     *
     * @return the value of ca_app_info_extend.is_auto_loan
     *
     * @mbg.generated
     */
    public Integer getIsAutoLoan() {
        return isAutoLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.is_auto_loan
     *
     * @param isAutoLoan the value for ca_app_info_extend.is_auto_loan
     *
     * @mbg.generated
     */
    public void setIsAutoLoan(Integer isAutoLoan) {
        this.isAutoLoan = isAutoLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.apply_time
     *
     * @return the value of ca_app_info_extend.apply_time
     *
     * @mbg.generated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.apply_time
     *
     * @param applyTime the value for ca_app_info_extend.apply_time
     *
     * @mbg.generated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.one_level
     *
     * @return the value of ca_app_info_extend.one_level
     *
     * @mbg.generated
     */
    public Integer getOneLevel() {
        return oneLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.one_level
     *
     * @param oneLevel the value for ca_app_info_extend.one_level
     *
     * @mbg.generated
     */
    public void setOneLevel(Integer oneLevel) {
        this.oneLevel = oneLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.two_level
     *
     * @return the value of ca_app_info_extend.two_level
     *
     * @mbg.generated
     */
    public Integer getTwoLevel() {
        return twoLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.two_level
     *
     * @param twoLevel the value for ca_app_info_extend.two_level
     *
     * @mbg.generated
     */
    public void setTwoLevel(Integer twoLevel) {
        this.twoLevel = twoLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.arrive
     *
     * @return the value of ca_app_info_extend.arrive
     *
     * @mbg.generated
     */
    public String getArrive() {
        return arrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.arrive
     *
     * @param arrive the value for ca_app_info_extend.arrive
     *
     * @mbg.generated
     */
    public void setArrive(String arrive) {
        this.arrive = arrive == null ? null : arrive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.final_wait
     *
     * @return the value of ca_app_info_extend.final_wait
     *
     * @mbg.generated
     */
    public Integer getFinalWait() {
        return finalWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.final_wait
     *
     * @param finalWait the value for ca_app_info_extend.final_wait
     *
     * @mbg.generated
     */
    public void setFinalWait(Integer finalWait) {
        this.finalWait = finalWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.first_examine_time
     *
     * @return the value of ca_app_info_extend.first_examine_time
     *
     * @mbg.generated
     */
    public Date getFirstExamineTime() {
        return firstExamineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.first_examine_time
     *
     * @param firstExamineTime the value for ca_app_info_extend.first_examine_time
     *
     * @mbg.generated
     */
    public void setFirstExamineTime(Date firstExamineTime) {
        this.firstExamineTime = firstExamineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.second_examine_time
     *
     * @return the value of ca_app_info_extend.second_examine_time
     *
     * @mbg.generated
     */
    public Date getSecondExamineTime() {
        return secondExamineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.second_examine_time
     *
     * @param secondExamineTime the value for ca_app_info_extend.second_examine_time
     *
     * @mbg.generated
     */
    public void setSecondExamineTime(Date secondExamineTime) {
        this.secondExamineTime = secondExamineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.final_examine_time
     *
     * @return the value of ca_app_info_extend.final_examine_time
     *
     * @mbg.generated
     */
    public Date getFinalExamineTime() {
        return finalExamineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.final_examine_time
     *
     * @param finalExamineTime the value for ca_app_info_extend.final_examine_time
     *
     * @mbg.generated
     */
    public void setFinalExamineTime(Date finalExamineTime) {
        this.finalExamineTime = finalExamineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.loan_before_time
     *
     * @return the value of ca_app_info_extend.loan_before_time
     *
     * @mbg.generated
     */
    public Date getLoanBeforeTime() {
        return loanBeforeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.loan_before_time
     *
     * @param loanBeforeTime the value for ca_app_info_extend.loan_before_time
     *
     * @mbg.generated
     */
    public void setLoanBeforeTime(Date loanBeforeTime) {
        this.loanBeforeTime = loanBeforeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.sub_status
     *
     * @return the value of ca_app_info_extend.sub_status
     *
     * @mbg.generated
     */
    public Integer getSubStatus() {
        return subStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.sub_status
     *
     * @param subStatus the value for ca_app_info_extend.sub_status
     *
     * @mbg.generated
     */
    public void setSubStatus(Integer subStatus) {
        this.subStatus = subStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.flow_status
     *
     * @return the value of ca_app_info_extend.flow_status
     *
     * @mbg.generated
     */
    public Integer getFlowStatus() {
        return flowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.flow_status
     *
     * @param flowStatus the value for ca_app_info_extend.flow_status
     *
     * @mbg.generated
     */
    public void setFlowStatus(Integer flowStatus) {
        this.flowStatus = flowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.fund_code
     *
     * @return the value of ca_app_info_extend.fund_code
     *
     * @mbg.generated
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.fund_code
     *
     * @param fundCode the value for ca_app_info_extend.fund_code
     *
     * @mbg.generated
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.message
     *
     * @return the value of ca_app_info_extend.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.message
     *
     * @param message the value for ca_app_info_extend.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.user_id
     *
     * @return the value of ca_app_info_extend.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.user_id
     *
     * @param userId the value for ca_app_info_extend.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.accept_status
     *
     * @return the value of ca_app_info_extend.accept_status
     *
     * @mbg.generated
     */
    public Integer getAcceptStatus() {
        return acceptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.accept_status
     *
     * @param acceptStatus the value for ca_app_info_extend.accept_status
     *
     * @mbg.generated
     */
    public void setAcceptStatus(Integer acceptStatus) {
        this.acceptStatus = acceptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.ltv_status
     *
     * @return the value of ca_app_info_extend.ltv_status
     *
     * @mbg.generated
     */
    public Integer getLtvStatus() {
        return ltvStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.ltv_status
     *
     * @param ltvStatus the value for ca_app_info_extend.ltv_status
     *
     * @mbg.generated
     */
    public void setLtvStatus(Integer ltvStatus) {
        this.ltvStatus = ltvStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.ltv_type
     *
     * @return the value of ca_app_info_extend.ltv_type
     *
     * @mbg.generated
     */
    public Integer getLtvType() {
        return ltvType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.ltv_type
     *
     * @param ltvType the value for ca_app_info_extend.ltv_type
     *
     * @mbg.generated
     */
    public void setLtvType(Integer ltvType) {
        this.ltvType = ltvType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.ltv_amount
     *
     * @return the value of ca_app_info_extend.ltv_amount
     *
     * @mbg.generated
     */
    public BigDecimal getLtvAmount() {
        return ltvAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.ltv_amount
     *
     * @param ltvAmount the value for ca_app_info_extend.ltv_amount
     *
     * @mbg.generated
     */
    public void setLtvAmount(BigDecimal ltvAmount) {
        this.ltvAmount = ltvAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.historical_records
     *
     * @return the value of ca_app_info_extend.historical_records
     *
     * @mbg.generated
     */
    public String getHistoricalRecords() {
        return historicalRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.historical_records
     *
     * @param historicalRecords the value for ca_app_info_extend.historical_records
     *
     * @mbg.generated
     */
    public void setHistoricalRecords(String historicalRecords) {
        this.historicalRecords = historicalRecords == null ? null : historicalRecords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.high_quality_user
     *
     * @return the value of ca_app_info_extend.high_quality_user
     *
     * @mbg.generated
     */
    public Integer getHighQualityUser() {
        return highQualityUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.high_quality_user
     *
     * @param highQualityUser the value for ca_app_info_extend.high_quality_user
     *
     * @mbg.generated
     */
    public void setHighQualityUser(Integer highQualityUser) {
        this.highQualityUser = highQualityUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.high_quality_user_status
     *
     * @return the value of ca_app_info_extend.high_quality_user_status
     *
     * @mbg.generated
     */
    public Integer getHighQualityUserStatus() {
        return highQualityUserStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.high_quality_user_status
     *
     * @param highQualityUserStatus the value for ca_app_info_extend.high_quality_user_status
     *
     * @mbg.generated
     */
    public void setHighQualityUserStatus(Integer highQualityUserStatus) {
        this.highQualityUserStatus = highQualityUserStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.first_upload_after_annex_time
     *
     * @return the value of ca_app_info_extend.first_upload_after_annex_time
     *
     * @mbg.generated
     */
    public Date getFirstUploadAfterAnnexTime() {
        return firstUploadAfterAnnexTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.first_upload_after_annex_time
     *
     * @param firstUploadAfterAnnexTime the value for ca_app_info_extend.first_upload_after_annex_time
     *
     * @mbg.generated
     */
    public void setFirstUploadAfterAnnexTime(Date firstUploadAfterAnnexTime) {
        this.firstUploadAfterAnnexTime = firstUploadAfterAnnexTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.last_upload_after_annex_time
     *
     * @return the value of ca_app_info_extend.last_upload_after_annex_time
     *
     * @mbg.generated
     */
    public Date getLastUploadAfterAnnexTime() {
        return lastUploadAfterAnnexTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.last_upload_after_annex_time
     *
     * @param lastUploadAfterAnnexTime the value for ca_app_info_extend.last_upload_after_annex_time
     *
     * @mbg.generated
     */
    public void setLastUploadAfterAnnexTime(Date lastUploadAfterAnnexTime) {
        this.lastUploadAfterAnnexTime = lastUploadAfterAnnexTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.cost_rate
     *
     * @return the value of ca_app_info_extend.cost_rate
     *
     * @mbg.generated
     */
    public BigDecimal getCostRate() {
        return costRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.cost_rate
     *
     * @param costRate the value for ca_app_info_extend.cost_rate
     *
     * @mbg.generated
     */
    public void setCostRate(BigDecimal costRate) {
        this.costRate = costRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.status_update_desc
     *
     * @return the value of ca_app_info_extend.status_update_desc
     *
     * @mbg.generated
     */
    public String getStatusUpdateDesc() {
        return statusUpdateDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.status_update_desc
     *
     * @param statusUpdateDesc the value for ca_app_info_extend.status_update_desc
     *
     * @mbg.generated
     */
    public void setStatusUpdateDesc(String statusUpdateDesc) {
        this.statusUpdateDesc = statusUpdateDesc == null ? null : statusUpdateDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.status_update_time
     *
     * @return the value of ca_app_info_extend.status_update_time
     *
     * @mbg.generated
     */
    public Date getStatusUpdateTime() {
        return statusUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.status_update_time
     *
     * @param statusUpdateTime the value for ca_app_info_extend.status_update_time
     *
     * @mbg.generated
     */
    public void setStatusUpdateTime(Date statusUpdateTime) {
        this.statusUpdateTime = statusUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.ser_fin_label
     *
     * @return the value of ca_app_info_extend.ser_fin_label
     *
     * @mbg.generated
     */
    public String getSerFinLabel() {
        return serFinLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.ser_fin_label
     *
     * @param serFinLabel the value for ca_app_info_extend.ser_fin_label
     *
     * @mbg.generated
     */
    public void setSerFinLabel(String serFinLabel) {
        this.serFinLabel = serFinLabel == null ? null : serFinLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.car_secure_rule_id
     *
     * @return the value of ca_app_info_extend.car_secure_rule_id
     *
     * @mbg.generated
     */
    public Integer getCarSecureRuleId() {
        return carSecureRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.car_secure_rule_id
     *
     * @param carSecureRuleId the value for ca_app_info_extend.car_secure_rule_id
     *
     * @mbg.generated
     */
    public void setCarSecureRuleId(Integer carSecureRuleId) {
        this.carSecureRuleId = carSecureRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_app_info_extend.webank_first_result
     *
     * @return the value of ca_app_info_extend.webank_first_result
     *
     * @mbg.generated
     */
    public String getWebankFirstResult() {
        return webankFirstResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_app_info_extend.webank_first_result
     *
     * @param webankFirstResult the value for ca_app_info_extend.webank_first_result
     *
     * @mbg.generated
     */
    public void setWebankFirstResult(String webankFirstResult) {
        this.webankFirstResult = webankFirstResult == null ? null : webankFirstResult.trim();
    }
}